before_script:
    - ls -la
    - apt-get update -y
    - apt-get install gcc g++ gfortran make cmake zlib1g-dev python-dateutil python-pyparsing python-numpy python-matplotlib python-pip python-setuptools python-dev -y
gcc_debug:
    script:
        - "python setup.py --cxx=g++ --cc=gcc --fc=gfortran --type=debug"
        - cd build
        - make
        - ctest
gcc_debug_nocxx11:
    script:
        - "python setup.py --cxx=g++ --cc=gcc --fc=gfortran --type=debug --cmake-options='-DENABLE_CXX11_SUPPORT=OFF'"
        - cd build
        - make
        - ctest
