language: cpp
git:
  submodules: false
before_install:
  - DEPS_DIR="${HOME}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
  - sudo apt-get update -y
  - sudo apt-get install -y gcc g++ gfortran make zlib1g-dev python-dev
  - mkdir ${DEPS_DIR}/cmake
  - wget --no-check-certificate https://cmake.org/files/v3.4/cmake-3.4.3-Linux-x86_64.tar.gz
  - tar --strip-components=1 -xzf cmake-3.4.3-Linux-x86_64.tar.gz -C cmake
  - export PATH=${DEPS_DIR}/cmake/bin:$PATH
  - cd -
  - cmake --version
  - gcc --version
  - g++ --version
  - gfortran --version
  - python --version
script:
  - python setup.py --cxx=g++ --cc=gcc --fc=gfortran --type=debug --cmake-options='-Hprojects/CMake -DENABLE_FORTRAN_API=ON'
  - cd build
  - VERBOSE=1 make
  - ctest -V
